export const CF_GET    = "https://watchgetproducts-if2wton52a-rj.a.run.app"
export const CF_CREATE = "https://watchcreateproduct-if2wton52a-rj.a.run.app"
export const CF_UPDATE = "https://watchupdateproduct-if2wton52a-rj.a.run.app"
export const CF_DELETE = "https://watchdeleteproduct-if2wton52a-rj.a.run.app"
export const CF_UPLOAD = "https://watchuploadimage-if2wton52a-rj.a.run.app"
