steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'shopify-crud'
    args:
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/shopify-crud/shopify-crud:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/shopify-crud/shopify-crud:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'shopify-crud'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/shopify-crud/shopify-crud:latest'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/shopify-crud/shopify-crud:latest'

options:
  logging: CLOUD_LOGGING_ONLY
